name: moans
description: Moans App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  audio_video_progress_bar: ^0.10.0
  permission_handler: ^8.3.0
  file_picker: ^4.3.0
  just_audio: ^0.9.18
  audio_service: ^0.18.3
  record: ^3.0.2
  audio_session: ^0.1.6+1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.11
  fluttertoast: ^8.0.8
  google_sign_in: ^5.2.1
  flutter_native_splash: ^2.1.1
  share_plus: ^4.0.3
  app_links: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  google_fonts: ^2.1.0
  
flutter:
  uses-material-design: true
  assets:
  - assets/back/back.png
  - assets/back/backfeed.png
  - assets/back/backrecord.png
  - assets/items/arrow.png
  - assets/items/feedon.png
  - assets/items/feedoff.png
  - assets/items/recordon.png
  - assets/items/recordoff.png
  - assets/items/profileon.png
  - assets/items/profileoff.png
  - assets/items/play.png
  - assets/items/pause.png
  - assets/items/likeon.png
  - assets/items/likeoff.png
  - assets/items/share.png
  - assets/items/menu.png
  - assets/items/recordbut.png
  - assets/items/ok.png
  - assets/items/doc.png
  - assets/items/edit.png
  - assets/items/arrowright.png
  - assets/items/cross.png
  - assets/items/backbut.png
  - assets/items/checkmark.png
  - assets/items/hint.png
  - assets/items/googlelogo.png

flutter_native_splash:
  background_image: "assets/logo/logo.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"